### PR TITLE
Increasing the number of records to retrieve

### PR DESCRIPTION
**Pull request by Upellift99**
By default, only the first 20 records can be retrieved, and you can have more :)

Thank you very much for your work!

### CODE REVIEW

**Comment by hyecheol123** [comment]
Thanks for the pull request. Once I test the code, I will merge it!!

**Comment by hyecheol123** [comment]
@Upellift99 Sorry for the late reply.
If we able to set up the number of records to be retrieved, it will be great.

Rather than using arbitrary big number, we can endorse it to the user.

**Comment by Upellift99** [comment]
Thanks for your reply @hyecheol123!
I agree, but, unfortunately, there is not any function in the API to retrieve the number of records:
https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records

It would be also a bit complicated to do a first request to get the number of records, then to pass it to list the records. Finally, why not putting immediately the maximum number of records to list, which is 100? And it would be simplier for the user.

In the same spirit, I see that the maximum value is already used to list all the zones, which is 50 in this case.
https://api.cloudflare.com/#zone-list-zones

What do you think?

**Review by hyecheol123 — APPROVED** [review]

**Comment by hyecheol123** [comment]
I merged this PR!! Sorry for being late :(

**Comment by Upellift99** [comment]
Great! Thank you again :)

**Pull request merged**
