### PR TITLE
Support API Token and support mutiple records has same name, eg: A & TXT

### PR DESCRIPTION
**Pull request by Rp70**
I want to add support for API Token and mutiple records has same name, eg: A & TXT. I also changed the way we pass HTTP Headers to curl. Let me know if you have any questions. Thank you!

### CODE REVIEW

**Comment by hyecheol123** [comment]
Oh, I did not think about multiple records having same name.
Looks like the types of record has been hard-coded, and I will further modify the code before merge so that I can figure out proper way to put those along with the update targets.

Moreover, this is something related to #4 , and this is one of my future improvement plan of this scripts.

Thanks for providing me a valuable improvement!!

**Comment by hyecheol123** [comment]
@Rp70 Do you prefer me to merge your code to a separated branch before I modify your code, or to work on your repository (By submitting PR on your branch) then merge the final work to my repository's master branch?

**Comment by Rp70** [comment]
> @Rp70 Do you prefer me to merge your code to a separated branch before I modify your code, or to work on your repository (By submitting PR on your branch) then merge the final work to my repository's master branch?

Hi! I'm new to GitHub and all kinds of git things so please feel free to do what you see it's convenient to you. I need to learn the both ways. Thank you!

**Comment by hyecheol123** [comment]
> Hi! I'm new to GitHub and all kinds of git things so please feel free to do what you see it's convenient to you. I need to learn the both ways. Thank you!

I prefer to work on your repository and merge fresh codes here.

- You do not need to create any additional PR to update. This PR will automatically updated once the code changed.
- I will work on your repository, and you can review my change before we go

Again, thanks for your feedbacks.

**Comment by Rp70** [comment]
I see the new update. Thanks so much!

**Comment by hyecheol123** [comment]
@Rp70 I tested the code, but if there's bug, please let me know.

Again, Thanks for your contribution

**Comment by altanalaybeyoglu** [comment]
> Hi,
> When I execute cloudflare_dynamic_ip_update.bash, I take "Error While updating .... " message.
> I check, API's Permissions. They are ok.
> Also My APIKey is working too
> 
> Thanks for script!

I think, It is about CF. My domain is example.tk so they say "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain)."

**Pull request merged**
